-- updated_at: missing on every table so far
ALTER TABLE availability ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();
ALTER TABLE classroom ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();
ALTER TABLE course ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();
ALTER TABLE institution ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();
ALTER TABLE professor ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();
ALTER TABLE professor_qualification ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();
ALTER TABLE schedule ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();
ALTER TABLE schedule_entry ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();
ALTER TABLE semester ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();
ALTER TABLE subject ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();
ALTER TABLE subject_offering ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();
ALTER TABLE time_slot ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();
ALTER TABLE users ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();

-- created_at: institution and users already have it since V2/V3
ALTER TABLE availability ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();
ALTER TABLE classroom ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();
ALTER TABLE course ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();
ALTER TABLE professor ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();
ALTER TABLE professor_qualification ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();
ALTER TABLE schedule ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();
ALTER TABLE schedule_entry ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();
ALTER TABLE semester ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();
ALTER TABLE subject ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();
ALTER TABLE subject_offering ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();
ALTER TABLE time_slot ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();
