from enum import StrEnum

class DayOfWeek(StrEnum):
    MONDAY = "MONDAY"
    TUESDAY = "TUESDAY"
    WEDNESDAY = "WEDNESDAY"
    THURSDAY = "THURSDAY"
    FRIDAY = "FRIDAY"
    SATURDAY = "SATURDAY"
    SUNDAY = "SUNDAY"

class RoomType(StrEnum):
    COMMON = "COMMON"
    LABORATORY = "LABORATORY"
    AUDITORIUM = "AUDITORIUM"
    COMPUTER_LAB = "COMPUTER_LAB"