/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin.index'
import { Route as SuperAdminEstruturaAcademicaRouteImport } from './routes/super-admin.estrutura-academica'
import { Route as SuperAdminGradesRouteImport } from './routes/super-admin.grades'
import { Route as SuperAdminInfraestruturaRouteImport } from './routes/super-admin.infraestrutura'
import { Route as SuperAdminInstituicoesRouteImport } from './routes/super-admin.instituicoes'
import { Route as SuperAdminProfessoresRouteImport } from './routes/super-admin.professores'
import { Route as SuperAdminUsuariosRouteImport } from './routes/super-admin.usuarios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminEstruturaAcademicaRoute =
  SuperAdminEstruturaAcademicaRouteImport.update({
    id: '/estrutura-academica',
    path: '/estrutura-academica',
    getParentRoute: () => SuperAdminRoute,
  } as any)
const SuperAdminGradesRoute = SuperAdminGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminInfraestruturaRoute =
  SuperAdminInfraestruturaRouteImport.update({
    id: '/infraestrutura',
    path: '/infraestrutura',
    getParentRoute: () => SuperAdminRoute,
  } as any)
const SuperAdminInstituicoesRoute = SuperAdminInstituicoesRouteImport.update({
  id: '/instituicoes',
  path: '/instituicoes',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminProfessoresRoute = SuperAdminProfessoresRouteImport.update({
  id: '/professores',
  path: '/professores',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminUsuariosRoute = SuperAdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => SuperAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/super-admin/estrutura-academica': typeof SuperAdminEstruturaAcademicaRoute
  '/super-admin/grades': typeof SuperAdminGradesRoute
  '/super-admin/infraestrutura': typeof SuperAdminInfraestruturaRoute
  '/super-admin/instituicoes': typeof SuperAdminInstituicoesRoute
  '/super-admin/professores': typeof SuperAdminProfessoresRoute
  '/super-admin/usuarios': typeof SuperAdminUsuariosRoute
  '/super-admin/': typeof SuperAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/super-admin/estrutura-academica': typeof SuperAdminEstruturaAcademicaRoute
  '/super-admin/grades': typeof SuperAdminGradesRoute
  '/super-admin/infraestrutura': typeof SuperAdminInfraestruturaRoute
  '/super-admin/instituicoes': typeof SuperAdminInstituicoesRoute
  '/super-admin/professores': typeof SuperAdminProfessoresRoute
  '/super-admin/usuarios': typeof SuperAdminUsuariosRoute
  '/super-admin': typeof SuperAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/super-admin/estrutura-academica': typeof SuperAdminEstruturaAcademicaRoute
  '/super-admin/grades': typeof SuperAdminGradesRoute
  '/super-admin/infraestrutura': typeof SuperAdminInfraestruturaRoute
  '/super-admin/instituicoes': typeof SuperAdminInstituicoesRoute
  '/super-admin/professores': typeof SuperAdminProfessoresRoute
  '/super-admin/usuarios': typeof SuperAdminUsuariosRoute
  '/super-admin/': typeof SuperAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/esqueci-senha'
    | '/login'
    | '/super-admin'
    | '/super-admin/estrutura-academica'
    | '/super-admin/grades'
    | '/super-admin/infraestrutura'
    | '/super-admin/instituicoes'
    | '/super-admin/professores'
    | '/super-admin/usuarios'
    | '/super-admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/esqueci-senha'
    | '/login'
    | '/super-admin/estrutura-academica'
    | '/super-admin/grades'
    | '/super-admin/infraestrutura'
    | '/super-admin/instituicoes'
    | '/super-admin/professores'
    | '/super-admin/usuarios'
    | '/super-admin'
  id:
    | '__root__'
    | '/'
    | '/esqueci-senha'
    | '/login'
    | '/super-admin'
    | '/super-admin/estrutura-academica'
    | '/super-admin/grades'
    | '/super-admin/infraestrutura'
    | '/super-admin/instituicoes'
    | '/super-admin/professores'
    | '/super-admin/usuarios'
    | '/super-admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  LoginRoute: typeof LoginRoute
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/estrutura-academica': {
      id: '/super-admin/estrutura-academica'
      path: '/estrutura-academica'
      fullPath: '/super-admin/estrutura-academica'
      preLoaderRoute: typeof SuperAdminEstruturaAcademicaRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/grades': {
      id: '/super-admin/grades'
      path: '/grades'
      fullPath: '/super-admin/grades'
      preLoaderRoute: typeof SuperAdminGradesRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/infraestrutura': {
      id: '/super-admin/infraestrutura'
      path: '/infraestrutura'
      fullPath: '/super-admin/infraestrutura'
      preLoaderRoute: typeof SuperAdminInfraestruturaRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/instituicoes': {
      id: '/super-admin/instituicoes'
      path: '/instituicoes'
      fullPath: '/super-admin/instituicoes'
      preLoaderRoute: typeof SuperAdminInstituicoesRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/professores': {
      id: '/super-admin/professores'
      path: '/professores'
      fullPath: '/super-admin/professores'
      preLoaderRoute: typeof SuperAdminProfessoresRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/usuarios': {
      id: '/super-admin/usuarios'
      path: '/usuarios'
      fullPath: '/super-admin/usuarios'
      preLoaderRoute: typeof SuperAdminUsuariosRouteImport
      parentRoute: typeof SuperAdminRoute
    }
  }
}

interface SuperAdminRouteChildren {
  SuperAdminEstruturaAcademicaRoute: typeof SuperAdminEstruturaAcademicaRoute
  SuperAdminGradesRoute: typeof SuperAdminGradesRoute
  SuperAdminInfraestruturaRoute: typeof SuperAdminInfraestruturaRoute
  SuperAdminInstituicoesRoute: typeof SuperAdminInstituicoesRoute
  SuperAdminProfessoresRoute: typeof SuperAdminProfessoresRoute
  SuperAdminUsuariosRoute: typeof SuperAdminUsuariosRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminEstruturaAcademicaRoute: SuperAdminEstruturaAcademicaRoute,
  SuperAdminGradesRoute: SuperAdminGradesRoute,
  SuperAdminInfraestruturaRoute: SuperAdminInfraestruturaRoute,
  SuperAdminInstituicoesRoute: SuperAdminInstituicoesRoute,
  SuperAdminProfessoresRoute: SuperAdminProfessoresRoute,
  SuperAdminUsuariosRoute: SuperAdminUsuariosRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  LoginRoute: LoginRoute,
  SuperAdminRoute: SuperAdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
