/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminEstruturaAcademicaRouteImport } from './routes/admin.estrutura-academica'
import { Route as AdminInfraestruturaRouteImport } from './routes/admin.infraestrutura'
import { Route as AdminInstituicoesRouteImport } from './routes/admin.instituicoes'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstruturaAcademicaRoute = AdminEstruturaAcademicaRouteImport.update({
  id: '/estrutura-academica',
  path: '/estrutura-academica',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInfraestruturaRoute = AdminInfraestruturaRouteImport.update({
  id: '/infraestrutura',
  path: '/infraestrutura',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstituicoesRoute = AdminInstituicoesRouteImport.update({
  id: '/instituicoes',
  path: '/instituicoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/admin/estrutura-academica': typeof AdminEstruturaAcademicaRoute
  '/admin/infraestrutura': typeof AdminInfraestruturaRoute
  '/admin/instituicoes': typeof AdminInstituicoesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/admin/estrutura-academica': typeof AdminEstruturaAcademicaRoute
  '/admin/infraestrutura': typeof AdminInfraestruturaRoute
  '/admin/instituicoes': typeof AdminInstituicoesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/admin/estrutura-academica': typeof AdminEstruturaAcademicaRoute
  '/admin/infraestrutura': typeof AdminInfraestruturaRoute
  '/admin/instituicoes': typeof AdminInstituicoesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/esqueci-senha'
    | '/login'
    | '/admin/estrutura-academica'
    | '/admin/infraestrutura'
    | '/admin/instituicoes'
    | '/admin/usuarios'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/esqueci-senha'
    | '/login'
    | '/admin/estrutura-academica'
    | '/admin/infraestrutura'
    | '/admin/instituicoes'
    | '/admin/usuarios'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/esqueci-senha'
    | '/login'
    | '/admin/estrutura-academica'
    | '/admin/infraestrutura'
    | '/admin/instituicoes'
    | '/admin/usuarios'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estrutura-academica': {
      id: '/admin/estrutura-academica'
      path: '/estrutura-academica'
      fullPath: '/admin/estrutura-academica'
      preLoaderRoute: typeof AdminEstruturaAcademicaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/infraestrutura': {
      id: '/admin/infraestrutura'
      path: '/infraestrutura'
      fullPath: '/admin/infraestrutura'
      preLoaderRoute: typeof AdminInfraestruturaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/instituicoes': {
      id: '/admin/instituicoes'
      path: '/instituicoes'
      fullPath: '/admin/instituicoes'
      preLoaderRoute: typeof AdminInstituicoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminEstruturaAcademicaRoute: typeof AdminEstruturaAcademicaRoute
  AdminInfraestruturaRoute: typeof AdminInfraestruturaRoute
  AdminInstituicoesRoute: typeof AdminInstituicoesRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEstruturaAcademicaRoute: AdminEstruturaAcademicaRoute,
  AdminInfraestruturaRoute: AdminInfraestruturaRoute,
  AdminInstituicoesRoute: AdminInstituicoesRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
