spring.application.name=optisched-api
spring.datasource.url=jdbc:postgresql://localhost:5432/optisched
spring.datasource.username=vinibarros
spring.datasource.password=vini@30062019

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true